name: Build

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Check out Examples repository
      uses: actions/checkout@v2
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Run PlatformIO
      run: |
        platformio run -d Projects/Button
        platformio run -d Projects/Controller_motor
        platformio run -d Projects/Dc_motor
        platformio run -d Projects/Distance
        platformio run -d Projects/Dxl
        platformio run -d Projects/Gate
        platformio run -d Projects/Gpio
        platformio run -d Projects/Imu
        platformio run -d Projects/Led
        platformio run -d Projects/Led_strip
        platformio run -d Projects/Light_sensor
        platformio run -d Projects/Load
        platformio run -d Projects/Potentiometer
        platformio run -d Projects/Power_switch
        platformio run -d Projects/Servo
        platformio run -d Projects/Stepper
        platformio run -d Projects/Bike_alarm/Alarm_controller
        platformio run -d Projects/Bike_alarm/Start_controller


